server:
 port: 8081

spring:
 datasource:
  type: com.zaxxer.hikari.HikariDataSource
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: "jdbc:mysql://localhost:3306/ysx?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai"
  username: root
  password: root
  hikari:
   pool-name: DateHikariCP
   minimum-idle: 5
   idle-timeout: 180000
   maximum-pool-size: 10
   auto-commit: true
   max-lifetime: 190000
   connection-timeout: 30000
   connection-test-query: select 1
 redis:
   timeout: 10000ms
   host: 127.0.0.1
   port: 6379
   database: 0 # 选择哪个库，默认0库
   lettuce:
    pool:
     max-active: 1024 # 最大连接数，默认 8
     max-wait: 10000ms # 最大连接阻塞等待时间，单位毫秒，默认 -1
     max-idle: 200 # 最大空闲连接，默认 8
     min-idle: 5


mybatis-plus:

 mapper-locations: classpath*:/mapper/*Mapper.xml
 #配置mybatis数据返回类型别名
 type-aliases-package: com.wei.ysx.entity
 configuration:
  # 自动驼峰命名
  map-underscore-to-camel-case: true

logging:
 level:
  com.wei.ysx.mapper: debug

goods_prefix: goods_





